/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author LUCA
 */
public class Devolucion extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Devolucion() {
        initComponents();
        this.lbErrorEstudiante.setText("");
        this.lbErrorLibro.setText("");
        this.lbErrorFecha.setText("");
        this.txtNombre.setEnabled(false);
        this.txtApellido.setEnabled(false);
        this.txtDni.setEnabled(false);
        this.txtCurso.setEnabled(false);
        this.txtDivision.setEnabled(false);
        this.txtTitulo.setEnabled(false);
        this.txtEdicion.setEnabled(false);
        this.txtIsbn.setEnabled(false);
        this.txtAutor.setEnabled(false);
        this.txtEditorial.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customUI1 = new necesario.CustomUI();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new RSMaterialComponent.RSButtonIconOne();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtBuscarDni = new RSMaterialComponent.RSTextFieldMaterial();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombre = new RSMaterialComponent.RSTextFieldMaterial();
        txtApellido = new RSMaterialComponent.RSTextFieldMaterial();
        txtDni = new RSMaterialComponent.RSTextFieldMaterial();
        lbErrorEstudiante = new javax.swing.JLabel();
        txtCurso = new RSMaterialComponent.RSTextFieldMaterial();
        txtDivision = new RSMaterialComponent.RSTextFieldMaterial();
        btnBuscarEstudiante = new RSMaterialComponent.RSButtonIconOne();
        jPanel4 = new javax.swing.JPanel();
        txtBuscarIsbn = new RSMaterialComponent.RSTextFieldMaterial();
        jSeparator3 = new javax.swing.JSeparator();
        txtTitulo = new RSMaterialComponent.RSTextFieldMaterial();
        txtEdicion = new RSMaterialComponent.RSTextFieldMaterial();
        txtIsbn = new RSMaterialComponent.RSTextFieldMaterial();
        lbErrorLibro = new javax.swing.JLabel();
        txtAutor = new RSMaterialComponent.RSTextFieldMaterial();
        txtEditorial = new RSMaterialComponent.RSTextFieldMaterial();
        btnBuscarLibro = new RSMaterialComponent.RSButtonIconOne();
        jPanel5 = new javax.swing.JPanel();
        lbErrorFecha = new javax.swing.JLabel();
        dtDevolucion = new rojeru_san.componentes.RSDateChooser();
        btnAceptar = new RSMaterialComponent.RSButtonIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(137, 122, 84));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Biblioteca - Programación II");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Devoluciones");

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(137, 122, 84));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PANEL DE DEVOLUCIONES");

        jSeparator1.setBackground(new java.awt.Color(137, 122, 84));
        jSeparator1.setForeground(new java.awt.Color(137, 122, 84));
        jSeparator1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(137, 122, 84));

        txtBuscarDni.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscarDni.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtBuscarDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscarDni.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarDni.setPlaceholder("Buscar DNI...");
        txtBuscarDni.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDniActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombre.setPhColor(new java.awt.Color(0, 0, 0));
        txtNombre.setPlaceholder("Nombre");
        txtNombre.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        txtApellido.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellido.setPhColor(new java.awt.Color(0, 0, 0));
        txtApellido.setPlaceholder("Apellido");
        txtApellido.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtDni.setForeground(new java.awt.Color(51, 51, 51));
        txtDni.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDni.setPhColor(new java.awt.Color(0, 0, 0));
        txtDni.setPlaceholder("DNI");
        txtDni.setSelectionColor(new java.awt.Color(0, 0, 0));

        lbErrorEstudiante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbErrorEstudiante.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErrorEstudiante.setText("Ingrese los datos correctos!");

        txtCurso.setForeground(new java.awt.Color(51, 51, 51));
        txtCurso.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCurso.setPhColor(new java.awt.Color(0, 0, 0));
        txtCurso.setPlaceholder("Curso");
        txtCurso.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtDivision.setForeground(new java.awt.Color(51, 51, 51));
        txtDivision.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDivision.setPhColor(new java.awt.Color(0, 0, 0));
        txtDivision.setPlaceholder("Division");
        txtDivision.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnBuscarEstudiante.setBackground(new java.awt.Color(92, 75, 66));
        btnBuscarEstudiante.setBackgroundHover(new java.awt.Color(171, 153, 105));
        btnBuscarEstudiante.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarDni, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbErrorEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbErrorEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(171, 153, 105));

        txtBuscarIsbn.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscarIsbn.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtBuscarIsbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscarIsbn.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarIsbn.setPlaceholder("Buscar ISBN...");
        txtBuscarIsbn.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtBuscarIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarIsbnActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTitulo.setPhColor(new java.awt.Color(0, 0, 0));
        txtTitulo.setPlaceholder("Titulo");
        txtTitulo.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtEdicion.setForeground(new java.awt.Color(51, 51, 51));
        txtEdicion.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtEdicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEdicion.setPhColor(new java.awt.Color(0, 0, 0));
        txtEdicion.setPlaceholder("Edición");
        txtEdicion.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtIsbn.setForeground(new java.awt.Color(51, 51, 51));
        txtIsbn.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtIsbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIsbn.setPhColor(new java.awt.Color(0, 0, 0));
        txtIsbn.setPlaceholder("ISBN");
        txtIsbn.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        lbErrorLibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbErrorLibro.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErrorLibro.setText("Ingrese los datos correctos!");

        txtAutor.setForeground(new java.awt.Color(51, 51, 51));
        txtAutor.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAutor.setPhColor(new java.awt.Color(0, 0, 0));
        txtAutor.setPlaceholder("Autor");
        txtAutor.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        txtEditorial.setForeground(new java.awt.Color(51, 51, 51));
        txtEditorial.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditorial.setPhColor(new java.awt.Color(0, 0, 0));
        txtEditorial.setPlaceholder("Editorial");
        txtEditorial.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnBuscarLibro.setBackground(new java.awt.Color(92, 75, 66));
        btnBuscarLibro.setBackgroundHover(new java.awt.Color(137, 122, 84));
        btnBuscarLibro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtBuscarIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbErrorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEdicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbErrorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(212, 191, 132));

        lbErrorFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbErrorFecha.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErrorFecha.setText("Ingrese los datos correctos!");

        dtDevolucion.setAlignmentY(1.0F);
        dtDevolucion.setAutoscrolls(true);
        dtDevolucion.setColorBackground(new java.awt.Color(92, 75, 66));
        dtDevolucion.setColorButtonHover(new java.awt.Color(171, 153, 105));
        dtDevolucion.setColorDiaActual(new java.awt.Color(212, 191, 132));
        dtDevolucion.setColorForeground(new java.awt.Color(137, 122, 84));
        dtDevolucion.setFormatoFecha("dd/MM/yyyy");
        dtDevolucion.setPlaceholder("Fecha de Devolución");

        btnAceptar.setBackground(new java.awt.Color(0, 153, 102));
        btnAceptar.setBackgroundHover(new java.awt.Color(0, 255, 102));
        btnAceptar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_CIRCLE);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDniActionPerformed

    }//GEN-LAST:event_txtBuscarDniActionPerformed

    private void txtBuscarIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarIsbnActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        validation.Validacion_Devolucion v = new validation.Validacion_Devolucion();
        if (v.validarBuscarLibro(this.txtBuscarIsbn, this.lbErrorLibro) == true) {
            bbdd.Consulta_Devolucion.buscarLibro(txtTitulo, txtEdicion, txtIsbn, txtAutor, txtEditorial, this.txtBuscarIsbn, this.lbErrorLibro);
        }
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        model.Devolucion d = new model.Devolucion();
        validation.Validacion_Devolucion v = new validation.Validacion_Devolucion();
        d.setNombre_estudiante(this.txtNombre.getText());
        d.setApellido_estudiante(this.txtApellido.getText());
        d.setDni_estudiante(this.txtDni.getText());
        d.setCurso_estudiante(this.txtCurso.getText());
        d.setDivision_estudiante(this.txtDivision.getText());
        d.setTitulo_libro(this.txtTitulo.getText());
        d.setEdicion_libro(this.txtEdicion.getText());
        d.setIsbn_libro(this.txtIsbn.getText());
        d.setAutor_libro(this.txtAutor.getText());
        d.setEditorial_libro(this.txtEditorial.getText());
        java.util.Date fecha = this.dtDevolucion.getDatoFecha();
        if (v.validarDevolucionEstudiante(this.txtNombre, this.txtApellido, this.txtDni, this.txtCurso, this.txtDivision, this.lbErrorEstudiante) == true
                && v.validarDevolucionLibro(this.txtTitulo, this.txtEdicion, this.txtIsbn, this.txtAutor, this.txtEditorial, this.lbErrorLibro) == true
                && v.validarBuscarEstudiante(this.txtBuscarDni, this.lbErrorFecha) == true
                && v.validarBuscarLibro(this.txtBuscarIsbn, this.lbErrorFecha) == true
                && v.validarFechaDevolucion(this.dtDevolucion, this.lbErrorFecha) == true) {
            java.sql.Date fechaSql = new java.sql.Date(fecha.getTime());
            d.setFecha_devolucion(fechaSql);
            if (bbdd.Consulta_Devolucion.registrarDevolucion(d)) {
                bbdd.Consulta_Devolucion.listarDevolucion("");
                this.lbErrorEstudiante.setText("");
                this.lbErrorLibro.setText("");
                this.lbErrorFecha.setText("");
                this.txtNombre.setText("");
                this.txtApellido.setText("");
                this.txtDni.setText("");
                this.txtCurso.setText("");
                this.txtDivision.setText("");
                this.txtTitulo.setText("");
                this.txtEdicion.setText("");
                this.txtIsbn.setText("");
                this.txtAutor.setText("");
                this.txtEditorial.setText("");
                SuccessAlert sa = new SuccessAlert();
                sa.setVisible(true);
                sa.setLocationRelativeTo(null);
                sa.setResizable(false);
            } else {
                DangerAlert da = new DangerAlert();
                da.setVisible(true);
                da.setLocationRelativeTo(null);
                da.setResizable(false);
            }
        }
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        validation.Validacion_Devolucion v = new validation.Validacion_Devolucion();
        if (v.validarBuscarEstudiante(this.txtBuscarDni, this.lbErrorEstudiante) == true) {
            bbdd.Consulta_Devolucion.buscarEstudiante(txtNombre, txtApellido, txtDni, txtCurso, txtDivision, this.txtBuscarDni, this.lbErrorEstudiante);
        }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnAceptar;
    private RSMaterialComponent.RSButtonIconOne btnBuscarEstudiante;
    private RSMaterialComponent.RSButtonIconOne btnBuscarLibro;
    private RSMaterialComponent.RSButtonIconOne btnSalir;
    private necesario.CustomUI customUI1;
    public rojeru_san.componentes.RSDateChooser dtDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lbErrorEstudiante;
    public javax.swing.JLabel lbErrorFecha;
    public javax.swing.JLabel lbErrorLibro;
    public RSMaterialComponent.RSTextFieldMaterial txtApellido;
    public RSMaterialComponent.RSTextFieldMaterial txtAutor;
    public RSMaterialComponent.RSTextFieldMaterial txtBuscarDni;
    public RSMaterialComponent.RSTextFieldMaterial txtBuscarIsbn;
    public RSMaterialComponent.RSTextFieldMaterial txtCurso;
    public RSMaterialComponent.RSTextFieldMaterial txtDivision;
    public RSMaterialComponent.RSTextFieldMaterial txtDni;
    public RSMaterialComponent.RSTextFieldMaterial txtEdicion;
    public RSMaterialComponent.RSTextFieldMaterial txtEditorial;
    public RSMaterialComponent.RSTextFieldMaterial txtIsbn;
    public RSMaterialComponent.RSTextFieldMaterial txtNombre;
    public RSMaterialComponent.RSTextFieldMaterial txtTitulo;
    // End of variables declaration//GEN-END:variables
}
