/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author LUCA
 */
public class Libro extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Libro() {
        initComponents();
        bbdd.Consulta_Libro.listarLibro("");
        this.lbError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new RSMaterialComponent.RSButtonIconOne();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterial();
        jSeparator2 = new javax.swing.JSeparator();
        txtEdicion = new RSMaterialComponent.RSTextFieldMaterial();
        txtIsbn = new RSMaterialComponent.RSTextFieldMaterial();
        txtAutor = new RSMaterialComponent.RSTextFieldMaterial();
        lbError = new javax.swing.JLabel();
        btnGuardar = new RSMaterialComponent.RSButtonIconOne();
        btnEditar = new RSMaterialComponent.RSButtonIconOne();
        btnEliminar = new RSMaterialComponent.RSButtonIconOne();
        btnBorrar = new RSMaterialComponent.RSButtonIconOne();
        txtEditorial = new RSMaterialComponent.RSTextFieldMaterial();
        txtTitulo = new RSMaterialComponent.RSTextFieldMaterial();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLibro = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(137, 122, 84));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Biblioteca - Programación II");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libros");

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setBackgroundHover(new java.awt.Color(255, 51, 51));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(137, 122, 84));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PANEL DE LIBROS");

        jSeparator1.setBackground(new java.awt.Color(137, 122, 84));
        jSeparator1.setForeground(new java.awt.Color(137, 122, 84));
        jSeparator1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(137, 122, 84));

        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscar.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        txtEdicion.setForeground(new java.awt.Color(51, 51, 51));
        txtEdicion.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtEdicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEdicion.setPhColor(new java.awt.Color(0, 0, 0));
        txtEdicion.setPlaceholder("Edición");
        txtEdicion.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtIsbn.setForeground(new java.awt.Color(51, 51, 51));
        txtIsbn.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtIsbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIsbn.setPhColor(new java.awt.Color(0, 0, 0));
        txtIsbn.setPlaceholder("ISBN");
        txtIsbn.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        txtAutor.setForeground(new java.awt.Color(51, 51, 51));
        txtAutor.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAutor.setPhColor(new java.awt.Color(0, 0, 0));
        txtAutor.setPlaceholder("Autor");
        txtAutor.setSelectionColor(new java.awt.Color(0, 0, 0));

        lbError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbError.setForeground(new java.awt.Color(204, 0, 0));
        lbError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbError.setText("Ingrese los datos correctos!");

        btnGuardar.setBackground(new java.awt.Color(0, 153, 102));
        btnGuardar.setBackgroundHover(new java.awt.Color(0, 255, 102));
        btnGuardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_CIRCLE);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(51, 51, 255));
        btnEditar.setBackgroundHover(new java.awt.Color(153, 153, 255));
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setBackgroundHover(new java.awt.Color(255, 102, 102));
        btnEliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 153, 0));
        btnBorrar.setBackgroundHover(new java.awt.Color(255, 204, 102));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        txtEditorial.setForeground(new java.awt.Color(51, 51, 51));
        txtEditorial.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditorial.setPhColor(new java.awt.Color(0, 0, 0));
        txtEditorial.setPlaceholder("Editorial");
        txtEditorial.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setColorMaterial(new java.awt.Color(77, 67, 47));
        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTitulo.setPhColor(new java.awt.Color(0, 0, 0));
        txtTitulo.setPlaceholder("Titulo");
        txtTitulo.setSelectionColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(txtEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbLibro.setBackground(new java.awt.Color(255, 255, 255));
        tbLibro.setForeground(new java.awt.Color(51, 51, 51));
        tbLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Titulo", "Edicion", "ISBN", "Autor", "Editorial"
            }
        ));
        tbLibro.setAltoHead(20);
        tbLibro.setColorBackgoundHead(new java.awt.Color(137, 122, 84));
        tbLibro.setColorBordeFilas(new java.awt.Color(204, 204, 204));
        tbLibro.setColorBordeHead(new java.awt.Color(204, 204, 204));
        tbLibro.setColorFilasForeground1(new java.awt.Color(177, 153, 105));
        tbLibro.setColorFilasForeground2(new java.awt.Color(177, 153, 105));
        tbLibro.setColorSelBackgound(new java.awt.Color(177, 153, 105));
        tbLibro.setSelectionBackground(new java.awt.Color(137, 122, 84));
        tbLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLibro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        model.Libro l = new model.Libro();
        validation.Validacion_Libro v = new validation.Validacion_Libro();
        l.setTitulo(this.txtTitulo.getText());
        l.setEdicion(this.txtEdicion.getText());
        l.setIsbn(this.txtIsbn.getText());
        l.setAutor(this.txtAutor.getText());
        l.setEditorial(this.txtEditorial.getText());
        if (v.validarLibro(this.txtTitulo, this.txtEdicion, this.txtIsbn, this.txtAutor, this.txtEditorial, this.lbError) == true) {
            if (bbdd.Consulta_Libro.buscarLibroRegistrado(l, this.lbError) == false) {
                bbdd.Consulta_Libro.listarLibro("");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        model.Libro l = new model.Libro();
        validation.Validacion_Libro v = new validation.Validacion_Libro();
        l.setTitulo(this.txtTitulo.getText());
        l.setEdicion(this.txtEdicion.getText());
        l.setIsbn(this.txtIsbn.getText());
        l.setAutor(this.txtAutor.getText());
        l.setEditorial(this.txtEditorial.getText());
        if (v.validarLibro(this.txtTitulo, this.txtEdicion, this.txtIsbn, this.txtAutor, this.txtEditorial, this.lbError) == true) {
            if (bbdd.Consulta_Libro.buscarLibroEditado(l, this.lbError) == true) {
                bbdd.Consulta_Libro.listarLibro("");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        model.Libro l = new model.Libro();
        validation.Validacion_Libro v = new validation.Validacion_Libro();
        l.setIsbn(this.txtIsbn.getText());
        if (v.validarLibro(this.txtTitulo, this.txtEdicion, this.txtIsbn, this.txtAutor, this.txtEditorial, this.lbError) == true) {
            if (bbdd.Consulta_Libro.buscarLibroEliminar(l, this.lbError) == true) {
                if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este libro?", "MENSAJE", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (bbdd.Consulta_Libro.eliminarLibro(l)) {
                        bbdd.Consulta_Libro.listarLibro("");
                        this.txtTitulo.setText("");
                        this.txtEdicion.setText("");
                        this.txtIsbn.setText("");
                        this.txtAutor.setText("");
                        this.txtEditorial.setText("");
                        this.lbError.setText("");
                        SuccessAlert sa = new SuccessAlert();
                        sa.setVisible(true);
                        sa.setLocationRelativeTo(null);
                        sa.setResizable(false);
                    } else {
                        DangerAlert da = new DangerAlert();
                        da.setVisible(true);
                        da.setLocationRelativeTo(null);
                        da.setResizable(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.txtTitulo.setText("");
        this.txtEdicion.setText("");
        this.txtIsbn.setText("");
        this.txtAutor.setText("");
        this.txtEditorial.setText("");
        this.lbError.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tbLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLibroMouseClicked
        int fila = this.tbLibro.getSelectedRow();
        this.txtTitulo.setText((String) this.tbLibro.getValueAt(fila, 1));
        this.txtEdicion.setText((String) this.tbLibro.getValueAt(fila, 2));
        this.txtIsbn.setText((String) this.tbLibro.getValueAt(fila, 3));
        this.txtAutor.setText((String) this.tbLibro.getValueAt(fila, 4));
        this.txtEditorial.setText((String) this.tbLibro.getValueAt(fila, 5));
    }//GEN-LAST:event_tbLibroMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        bbdd.Consulta_Libro.listarLibro(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnBorrar;
    private RSMaterialComponent.RSButtonIconOne btnEditar;
    private RSMaterialComponent.RSButtonIconOne btnEliminar;
    private RSMaterialComponent.RSButtonIconOne btnGuardar;
    private RSMaterialComponent.RSButtonIconOne btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lbError;
    public static rojerusan.RSTableMetro tbLibro;
    public RSMaterialComponent.RSTextFieldMaterial txtAutor;
    private RSMaterialComponent.RSTextFieldMaterial txtBuscar;
    public RSMaterialComponent.RSTextFieldMaterial txtEdicion;
    public RSMaterialComponent.RSTextFieldMaterial txtEditorial;
    public RSMaterialComponent.RSTextFieldMaterial txtIsbn;
    public RSMaterialComponent.RSTextFieldMaterial txtTitulo;
    // End of variables declaration//GEN-END:variables
}
