/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio3swing;

import javax.swing.JOptionPane;

/**
 *
 * @author luca_
 */
public class Register extends javax.swing.JDialog {

    /**
     * Creates new form Form
     */
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Register Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        jBtnAtras = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtDomicilio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbxUsuario = new javax.swing.JComboBox<>();
        jPwPassword = new javax.swing.JPasswordField();
        jPwRepeatPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE USUARIOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 302, 70));

        jBtnSalir.setBackground(new java.awt.Color(255, 51, 51));
        jBtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalir.setText("Salir");
        jBtnSalir.setToolTipText("Salir");
        jBtnSalir.setBorder(null);
        jBtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSalir.setFocusable(false);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, 84, 30));

        jBtnAtras.setBackground(new java.awt.Color(0, 51, 51));
        jBtnAtras.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAtras.setText("Volver Atrás");
        jBtnAtras.setBorder(null);
        jBtnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAtras.setFocusable(false);
        jBtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 36, 84, 34));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 54, 123, 25));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 17, 123, 25));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 128, 123, 25));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electrónico:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 91, 123, 25));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Repetir Contraseña:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 165, 123, 25));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Domicilio:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 202, 123, 25));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 239, 123, 25));

        jTxtNombre.setBackground(new java.awt.Color(153, 153, 153));
        jTxtNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtNombre.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 17, 292, -1));

        jTxtEmail.setBackground(new java.awt.Color(153, 153, 153));
        jTxtEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtEmail.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 91, 292, -1));

        jTxtApellido.setBackground(new java.awt.Color(153, 153, 153));
        jTxtApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtApellido.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jTxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 54, 292, -1));

        jTxtTelefono.setBackground(new java.awt.Color(153, 153, 153));
        jTxtTelefono.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jTxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 239, 292, -1));

        jTxtDomicilio.setBackground(new java.awt.Color(153, 153, 153));
        jTxtDomicilio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtDomicilio.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jTxtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 202, 292, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Usuario:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 277, 123, 25));

        jCbxUsuario.setBackground(new java.awt.Color(153, 153, 153));
        jCbxUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jCbxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comun", "Administrador" }));
        jCbxUsuario.setBorder(null);
        jPanel3.add(jCbxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 276, 292, -1));

        jPwPassword.setBackground(new java.awt.Color(153, 153, 153));
        jPwPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPwPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jPwPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 129, 292, -1));

        jPwRepeatPassword.setBackground(new java.awt.Color(153, 153, 153));
        jPwRepeatPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPwRepeatPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jPwRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 166, 292, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RECORDATORIO:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 314, 421, -1));

        jLabel11.setForeground(new java.awt.Color(255, 153, 51));
        jLabel11.setText("Las contraseñas válidas deben cumplir con los siguientes requisitos:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 341, 421, -1));

        jLabel12.setForeground(new java.awt.Color(255, 153, 51));
        jLabel12.setText("* Mínimo 8 caracteres (numeros, letras y signos).");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 363, 421, -1));

        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("* Mínimo 1 letra minúscula.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 385, 421, -1));

        jLabel14.setForeground(new java.awt.Color(255, 153, 51));
        jLabel14.setText("* Mínimo 1 letra mayúscula.");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 407, 421, -1));

        jLabel15.setForeground(new java.awt.Color(255, 153, 51));
        jLabel15.setText("* Mínimo 3 números y máximo 25 números.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 429, 421, -1));

        jLabel16.setForeground(new java.awt.Color(255, 153, 51));
        jLabel16.setText("* Mínimo 1 signo de los siguientes \"$&+,.:%;=@#|\", sin contar las comillas.");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 451, 421, -1));

        jBtnGuardar.setBackground(new java.awt.Color(0, 204, 102));
        jBtnGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setBorder(null);
        jBtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGuardar.setFocusable(false);
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 479, 202, 35));

        jBtnBorrar.setBackground(new java.awt.Color(102, 0, 0));
        jBtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBorrar.setText("Borrar Todo");
        jBtnBorrar.setBorder(null);
        jBtnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBorrar.setFocusable(false);
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 479, 207, 35));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 520));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo de Pantalla.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 460, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 459, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtrasActionPerformed
        Admin a = new Admin();
        this.setVisible(false);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        a.setResizable(false);
    }//GEN-LAST:event_jBtnAtrasActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        Usuario u = new Usuario();
            u.setNombre(this.jTxtNombre.getText());
            u.setApellido(this.jTxtApellido.getText());
            u.setEmail(this.jTxtEmail.getText());
            u.setPassword(this.jPwPassword.getText());
            u.setRepeatPassword(this.jPwRepeatPassword.getText());
            u.setDomicilio(this.jTxtDomicilio.getText());
            u.setTelefono(this.jTxtTelefono.getText());
            u.setUsertype((String) this.jCbxUsuario.getSelectedItem());
            if(u.validarUsuarioRegistrar() == 1){
                if(Consulta.registrarUsuario(u)){
                    Consulta.listarUsuarioAdmin("");
                    JOptionPane.showMessageDialog(null, "El Usuario se ha registrado correctamente","Mensaje", JOptionPane.INFORMATION_MESSAGE);  
                    this.setVisible(false);
                    Admin a = new Admin();
                    a.setVisible(true);
                    a.setLocationRelativeTo(null);
                    a.setResizable(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Ha Habido errores al registrar","Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        this.jTxtNombre.setText("");
        this.jTxtApellido.setText("");
        this.jTxtEmail.setText("");
        this.jPwPassword.setText("");
        this.jPwRepeatPassword.setText("");
        this.jTxtDomicilio.setText("");
        this.jTxtTelefono.setText("");
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register dialog = new Register(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAtras;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<String> jCbxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPwPassword;
    private javax.swing.JPasswordField jPwRepeatPassword;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtDomicilio;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
