/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2swing;

import javax.swing.JFileChooser;

/**
 *
 * @author LUKA28
 */
public class Login extends javax.swing.JFrame {

    Usuario u = new Usuario();

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jPwdPassword = new javax.swing.JPasswordField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnSalirUno = new javax.swing.JButton();
        jBtnPanelRecovery = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGRESO DE DATOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 500, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese una Contraseña:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 360, 24));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese un Correo Electrónico:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 24));

        jTxtEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTxtEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTxtEmail.setForeground(new java.awt.Color(51, 51, 51));
        jTxtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtEmail.setBorder(null);
        jPanel2.add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 30));

        jPwdPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPwdPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPwdPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPwdPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPwdPassword.setBorder(null);
        jPanel2.add(jPwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 360, 30));

        jBtnGuardar.setBackground(new java.awt.Color(0, 204, 102));
        jBtnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBtnGuardar.setText("Ingresar");
        jBtnGuardar.setBorder(null);
        jBtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 110, 40));

        jBtnSalirUno.setBackground(new java.awt.Color(255, 51, 51));
        jBtnSalirUno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnSalirUno.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalirUno.setText("Salir");
        jBtnSalirUno.setBorder(null);
        jBtnSalirUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSalirUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirUnoActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSalirUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 110, 40));

        jBtnPanelRecovery.setBackground(new java.awt.Color(102, 102, 255));
        jBtnPanelRecovery.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnPanelRecovery.setForeground(new java.awt.Color(51, 51, 51));
        jBtnPanelRecovery.setText("Recuperación");
        jBtnPanelRecovery.setBorder(null);
        jBtnPanelRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPanelRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPanelRecoveryActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnPanelRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 110, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Abed David - Eglez Matias - Lagos Luca");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 520, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2swing/fondo_de_pantalla.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 520, 230));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 520, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        u.email = jTxtEmail.getText();
        u.password = jPwdPassword.getText();
        if(u.validateDate() == 1){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnSalirUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirUnoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirUnoActionPerformed

    private void jBtnPanelRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPanelRecoveryActionPerformed
        Archivo a = new Archivo();
        this.setVisible(false);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        a.setSize(560, 310);
        a.setResizable(false);
    }//GEN-LAST:event_jBtnPanelRecoveryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnPanelRecovery;
    private javax.swing.JButton jBtnSalirUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPwdPassword;
    private javax.swing.JTextField jTxtEmail;
    // End of variables declaration//GEN-END:variables
}
